version: "3"
services:
    angular:
      build: ./Frontend/tweetapp
      container_name: angular
      ports: 
        - 4200:80  
      environment: 
        - baseUrl=http://springboot:9091  
      networks: 
        - tweetapp
    # docker-ngnix:
    #   container_name: docker-ngnix
    #   build: ./
    #   ports:
    #     - 80:80
    #   command: ["nginx", "-g","deamon off;"]
    #   depends_on: 
    #     - angular   

    springboot:
        build: ./Backend/tweetapp
        container_name: spring
        ports:
          - '9091:9091'
        environment:
          - MONGOHOST=mongo
          - MONGOPORT=27017
          - MONGODB=tweetapp
          - KAFKAHOST=kafka
          - KAFKAPORT=9092
            
        networks: 
          - tweetapp
        depends_on: 
          - mongo
          - kafka    
    mongo:
        image: 'mongo:latest'
        container_name: mongodb
        ports:
          - '27017:27017'
        networks: 
          - tweetapp          
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        container_name: zookeeper
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
          - tweetapp    
    kafka:
        image: 'bitnami/kafka:latest'
        container_name: kafka
        ports:
          - '9092:9092'
        environment: 
          - KAFKA_BROKER_ID=1
          - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
          - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
          - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
          - ALLOW_PLAINTEXT_LISTENER=yes
        networks: 
          - tweetapp  
        depends_on: 
          - zookeeper
    elasticsearch:
        image: 'elasticsearch:7.12.0'
        container_name: elasticsearch
        environment: 
          - discovery.type=single-node
        ports:
          - 9200:9200
        networks: 
          - tweetapp 
    logstash:
        build: ./Backend/tweetapp/LogstashDocker
        container_name: logstash
        ports:
          - 5044:5044
          - 9600:9600
        environment: 
          - ELASTICSEARCHHOST=elasticsearch
          - ELASTICSEARCHPORT=9200
          - KAFKAHOST=kafka
          - KAFKAPORT=9092
          - PATH_CONFIG=/usr/share/logstash/pipeline/logstash.conf
        networks: 
          - tweetapp
        depends_on: 
          - elasticsearch      
    kibana:
        image: 'kibana:7.12.0'
        container_name: kibana
        ports:
          - 5601:5601
        environment: 
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        networks: 
          - tweetapp
        depends_on: 
          - elasticsearch    

networks: 
   tweetapp: {}
